name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

permissions:
  contents: read

jobs:

  check:
    runs-on: ubuntu-latest
    name: Check w/ ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version:
        - v1.18
        - v1.20
        - v1.22
        - v2.0
        - v2.2
        - v2.4
        - canary
      fail-fast: false # run each branch to completion

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Run test suite
      run: deno test --allow-read=test test/*.js

  dry-run:
    runs-on: ubuntu-latest

    steps:
    - uses: denoland/setup-deno@v2

    - uses: actions/checkout@v5

    - name: Check publish rules
      run: time deno publish --dry-run --allow-dirty

  publish:
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'push'

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: denoland/setup-deno@v2

    - uses: actions/checkout@v5

    - name: Publish now
      run: deno publish
