name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

permissions:
  contents: read

jobs:

  check:
    runs-on: ubuntu-latest
    name: Check w/ ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version:
        - v1.40
        - v2.0
        - v2.1
        - v2.2
        - v2.3
        - v2.4
        - v2.5
        - canary
      fail-fast: false # run each branch to completion

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Cache Deno deps
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno
        key: deno/${{ matrix.deno-version }}-${{ github.sha }}

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: 'Possibly reset lockfile'
      run: deno install || rm deno.lock

    - name: Run test suite
      run: deno task test

  dry-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v5

    - name: Use stable Deno
      uses: denoland/setup-deno@v2

    - name: Cache Deno deps
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno
        key: deno/publish-${{ github.sha }}

    - name: Check publish rules
      run: time deno publish --dry-run --allow-dirty

  publish:
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'push'

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v5

    - name: Use stable Deno
      uses: denoland/setup-deno@v2

    - name: Cache Deno deps
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno
        key: deno/publish-${{ github.sha }}
    - name: Publish now
      run: deno publish
